### PR TITLE
Refactor unit tests and build system

### PR DESCRIPTION
**Pull request by iainchesworth**
The change to the unit testing refactors them so that they:
- provide an explicit pass/fail when executed as part of the CI system
- are not dependent on any external test files (input and output)
- are grouped into logical test blocks so that new tests can be added

The change to the build system refactors it so that:
- a modern CMake approach is taken for a C++ header-only library
- provides for installation of the header-only library
- adds support for building documentation when a top-level project

### CODE REVIEW

**Comment by DuffsDevice** [comment]
Hey Lain (I assume, that's your name),
you're the man!! Seriously, thank you soo much for taking your time! It looks very pertty, I could have never done that.
Perhaps, do you know, how to fix the tests on osx and windows? Linux will be just fine I think.
All the best,
Jakob

**Comment by iainchesworth** [comment]
I've refactored the build scripts a little to accomodate grabbing the GoogleTest dependency in slightly different ways and updated the unit tests so they now build and pass on all platforms.

I did have to fix an issue in the exception specifiers (see commit 6936535) which was incorrectly calculating the noexcept specifier when TINY_UTF8_NOEXCEPT was specified).  I've added unit tests which check this behaviour.

**Comment by DuffsDevice** [comment]
Nice! Again, thanks a lot for taking your time.
So, I would like to get your opinion on this: I initially had two different constructors taking let’s say a char-literal. One was enabled, if the literal would enable SSO and the other one kicked in if not. That’s also the reason they had two different exception specifications, because SSO does not necessitate a potentially throwing allocation.
This was the original intent of me and I assume it worked. Now, you said, that it would clash. Did that actually happen? I would like to keep both versions, so what do you think?
Yours,
Jakob

**Comment by DuffsDevice** [comment]
By the way, are you depending on the Pull request being merged very soon? If not, I’d appreciate to review it in 9 days from now, which is when I‘m back from a sailing trip in Italy. Otherwise I‘ll try to do it tomorrow during the day.
Please let me know!

**Comment by DuffsDevice** [comment]
Oh, and I have another question I’d like to know your opinion on: Do you think, supporting a source-file/header-file approach is desirable for a project of this size?

**Comment by iainchesworth** [comment]
> I initially had two different constructors taking let’s say a char-literal. One was enabled, if the literal would enable SSO and the other one kicked in if not. That’s also the reason they had two different exception specifications, because SSO does not necessitate a potentially throwing allocation.
> Now, you said, that it would clash. Did that actually happen? I would like to keep both versions, so what do you think?

The issue appears under the VS 2017 toolchain (i.e. toolset v141).  When both definitions are present, they appears to trigger a SINFAE bug which then prevents one of the definitions to be hidden and the compiler subsequently fails with a "duplicate function, different exception specifications" error.  I've not developed a way to bypass this issue as to not trigger the bug.

Related to this, Travis CI only provides the v141 toolset when compiling for Windows so there's no easy way to do CI without the build failing (if including the unit tests for constructors).

**Comment by DuffsDevice** [comment]
Wow, I just reviewed all changes for merging.
Thank you for your efforts!

**Pull request merged**
